### ISSUE TITLE
Why it wasn't updating...

### ISSUE THREAD

**Issue by beaniemonk** [qphandev/dice_game#1]
I think it's [here](https://github.com/qphandev/dice_game/blob/d528f0ed5b9768f531847ce8e0cd6ed9f3d681d4/src/components/Die.js#L15).

What's in the constructor is run only once when the component is first mounted. It doesn't run again when the component updates. So when your props change, state isn't getting updated with the new props. `shouldComponentUpdate()` "fixes" it because it's forcing that to happen.

Since you don't actually call `setState` in this component (you're just reading from props), you should be able to leave out state entirely and simplify this component down to:

```
function Die(props) {
    return (
        <FontAwesomeIcon onClick={props.onLockDie} className={`die ${props.dieLocked ? "red-border" : ""}`} icon={props.dieFace} size="4x" />
    )
}
```

**Comment by qphandev** [comment]
Whoa that's crazy. I was definitely overthinking it then. So the takeaway is I didn't actually need state in Die component, and what made it not render in the first place was because it was stateful but I wasn't using setState in Die.js? Whereas when it's a stateless component it reacts to the new props being passed in. I'm guessing this behavior is to prevent extra and unnecessary re-rendering of components? 

Thanks!

**Comment by beaniemonk** [comment]
It'll always react to changing props, stateless or not. As a matter of fact, anytime its parent re-renders, it will re-render too, even if *nothing* changes. (1)

And "re-render" in this case just means React re-runs the render function. It doesn't necessarily mean it updates the DOM. After re-rendering, *then* it compares it to the previous version and only updates the DOM if something is different. 

That's an important distinction, because "re-rendering" isn't as scary as it sounds. The expensive part (updating the DOM) only happens when it needs to. The part in between re-rendering and updating the DOM is what they call the "Shadow DOM" and is what gives React its performance benefits. So in other words, in React, re-rendering isn't necessarily a bad thing that you always have to avoid.

React Components have "phases" so to speak:

1. Mounting -- The first time it's rendered and added to the DOM. This is the *only* time that the `constructor()` runs. 
2. Updating -- Every subsequent re-render, caused by its parent re-rendering or by its state changing. (2)
3. Unmounting -- When it's being removed from the DOM and getting cleaned up.

For Class Components, you can make certain things happen during each phase by using its lifecycle methods:

```
class Foo extends Component {
    constructor(props) {
        super(props);
        // Stuff in here only happens right before "Mounting"
    }

    componentDidMount() {
        // Stuff in here only happens right after "Mounting"
        // 9 times out of 10 you're better off doing it in the constructor
    }

    componentDidUpdate(prevProps, prevState) {
        // Stuff in here only happens after "Updating" (note: not when "Mounting")
        // You can compare this.props to prevProps, and this.state to prevState to decide what to do
    }

    componentWillUnmount() {
        // Stuff in here only happens right before "Unmounting"
        // Typically this is stuff like cleaning up event listeners
    }
}
```

So to make your existing Die component work with state, you'd do something like:
```
class Die extends Component {
    constructor(props) {
        super(props);
        this.state = {
            dieFace: this.props.dieFace,
            dieValue: this.props.dieValue,
            dieLocked: this.props.dieLocked
        };
    }

    componentDidUpdate() {
        // Since this runs when anything updates -- props OR state -- you want to do
        // a check here before calling setState() to avoid an infinite loop
        if (
            prevProps.dieFace !== this.props.dieFace
            || prevProps.dieValue !== this.props.dieValue
            || prevProps.dieLocked !== this.props.dieLocked
        ) {
            this.setState({
                dieFace: this.props.dieFace,
                dieValue: this.props.dieValue,
                dieLocked: this.props.dieLocked
            });
        }
    }

    render () {
        return (
            <FontAwesomeIcon onClick={this.props.onLockDie} className={`die ${this.state.dieLocked ? "red-border" : ""}`} icon={this.state.dieFace} size="4x" />
        );
    }
}
```

But conventional wisdom is, if you're just setting state to whatever props are, it's better to just use the props directly and leave state out of the equation. And you can see how much simpler it is when you do that -- it's wonky having to repeat almost the exact same code in 2 places or do those tedious `if()` checks to avoid crashing your App. :)

So the gist is, you were setting state to your *initial* props, but not updating state when those props subsequently changed. And thus your Component didn't seem to be updating.

---

(1) - Exceptions would be if you used one of these 3 things:
1. [React.PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent)
2. [React.memo](https://reactjs.org/docs/react-api.html#reactmemo)
3. [shouldComponentUpdate()](https://reactjs.org/docs/react-component.html#shouldcomponentupdate)

All 3 are manual optimizations. A reason for using them would be if you *are* doing something expensive in your render function -- like looping through a huge array -- and want to cut down on unnecessary re-renders.

(2) - On each render, React uses special rules to decide whether it's updating an existing component, or mounting a new one. [You can read about it here](https://reactjs.org/docs/reconciliation.html). Generally speaking, you'd have to go out of your way to confuse it into doing one thing when you want the other. But it's helpful to keep in mind.
